### ISSUE TITLE
TFS Rest Api Password is in plain text

### ISSUE THREAD

**Issue by skylock** [gregpakes/ArtifactVariables#1]
First, tank you very much for the extension.

The TFS Rest Api Password needs to be obfuscated since is a password field.

**Comment by gregpakes** [comment]
I am assuming you mean on the settings page. Yes - Good point.

I'll take a look.

**Comment by skylock** [comment]
A workaround is to define it as variable and use the secret option, but for convenience can this secret option be enabled on the settings page ?

**Comment by gregpakes** [comment]
I've always used it by defining a variable and marking is secret.  I'm looking through the documentation to see if I can set it as secret on the extension.

**Comment by gregpakes** [comment]
I have looked through the official Microsoft tasks and so far I can't see how this can be done.  

I would have expected to see something here:  https://github.com/Microsoft/vsts-rm-extensions/blob/master/Extensions/IISWebAppDeploy/Src/Tasks/IISWebAppDeploy/task.json#L57

Reading their own description:

https://github.com/Microsoft/vsts-rm-extensions/blob/master/Extensions/IISWebAppDeploy/Src/Tasks/IISWebAppDeploy/task.json#L61

It states, the best practice is to use the variable approach.

I will close this as I don't believe it is possible.

**Comment by skylock** [comment]
Ok, thank you very much for your time !

One more time, very good job with this extension !
